"use strict";
exports.__esModule = true;
var express_1 = require("express");
require("express-async-errors");
var app = (0, express_1["default"])();
var _a = require("./middleware/errors"), notFoundHandler = _a.notFoundHandler, errorHandler = _a.errorHandler;
var admin_1 = require("./routes/admin");
var auth_1 = require("./routes/auth");
var member_1 = require("./routes/member");
var dotenv_1 = require("dotenv");
dotenv_1["default"].config();
app.use(express_1["default"].json());
app.use(express_1["default"].urlencoded({ extended: true }));
app.use("/api/v1/admin", admin_1["default"]);
app.use("/api/v1/auth", auth_1["default"]);
app.use("/api/v1/member", member_1["default"]);
app.use(notFoundHandler);
app.use(errorHandler);
app.listen(process.env.SERVER_PORT || 3000);
